platform :ios, '13.0'

# Disable CocoaPods stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matched = line.match(/FLUTTER_ROOT\=(.*)/)
    return matched[1].strip if matched
  end
  raise 'FLUTTER_ROOT not found. Please run flutter pub get first.'
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'), __FILE__)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -ObjC'
      # Strip unsupported '-G' flags if they appear
      %w[
        OTHER_CFLAGS
        OTHER_CPLUSPLUSFLAGS
        OTHER_LDFLAGS
        OTHER_SWIFT_FLAGS
        OTHER_LIBTOOLFLAGS
        OTHER_LINKER_FLAGS
      ].each do |key|
        val = config.build_settings[key]
        if val.is_a?(String)
          val = val.gsub(/\s\-G(\s|$)/, ' ')
          val = val.gsub(/\-G(\s|$)/, ' ')
          config.build_settings[key] = val
        elsif val.is_a?(Array)
          config.build_settings[key] = val.reject { |item| item.to_s =~ /^\-G(\b|$)/ }
        end
      end
      config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
    end
  end
end


